### ISSUE TITLE
Getting httpx.ProxyError: 403 Forbidden on PythonAnyWhere

### ISSUE THREAD

**Issue by lnxpy** [hugovk/pypistats#349]
I'm using your package in a module deployed on https://pythonanywhere.com, Once I run the script, it raises me the following exception:

```
  File "/home/pasteme/.virtualenvs/pasteme.pythonanywhere.com/lib/python3.8/site-packages/httpx/_client.py", line 902, in send                                                        
    response = self._send_handling_auth(                                                                                                                                              
  File "/home/pasteme/.virtualenvs/pasteme.pythonanywhere.com/lib/python3.8/site-packages/httpx/_client.py", line 930, in _send_handling_auth                                         
    response = self._send_handling_redirects(                                                                                                                                         
  File "/home/pasteme/.virtualenvs/pasteme.pythonanywhere.com/lib/python3.8/site-packages/httpx/_client.py", line 967, in _send_handling_redirects                                    
    response = self._send_single_request(request)                                                                                                                                     
  File "/home/pasteme/.virtualenvs/pasteme.pythonanywhere.com/lib/python3.8/site-packages/httpx/_client.py", line 1003, in _send_single_request                                       
    response = transport.handle_request(request)                                                                                                                                      
  File "/home/pasteme/.virtualenvs/pasteme.pythonanywhere.com/lib/python3.8/site-packages/httpx/_transports/default.py", line 218, in handle_request                                  
    resp = self._pool.handle_request(req)                                                                                                                                             
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__                                                                                                                      
    self.gen.throw(type, value, traceback)                                                                                                                                            
  File "/home/pasteme/.virtualenvs/pasteme.pythonanywhere.com/lib/python3.8/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions                          
    raise mapped_exc(message) from exc                                                                                                                                                
httpx.ProxyError: 403 Forbidden
```

Calling the API endpoint with `requests`:
```
>>> r = requests.get('https://pypistats.org/api/packages/pasteme-cli/overall')
Traceback (most recent call last):
  File "/home/pasteme/.virtualenvs/pasteme.pythonanywhere.com/lib/python3.8/site-packages/urllib3/connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "/home/pasteme/.virtualenvs/pasteme.pythonanywhere.com/lib/python3.8/site-packages/urllib3/connectionpool.py", line 996, in _prepare_proxy
    conn.connect()
  File "/home/pasteme/.virtualenvs/pasteme.pythonanywhere.com/lib/python3.8/site-packages/urllib3/connection.py", line 369, in connect
    self._tunnel()
  File "/usr/lib/python3.8/http/client.py", line 904, in _tunnel
    raise OSError("Tunnel connection failed: %d %s" % (code,
OSError: Tunnel connection failed: 403 Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pasteme/.virtualenvs/pasteme.pythonanywhere.com/lib/python3.8/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/pasteme/.virtualenvs/pasteme.pythonanywhere.com/lib/python3.8/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/home/pasteme/.virtualenvs/pasteme.pythonanywhere.com/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='pypistats.org', port=443): Max retries exceeded with url: /api/packages/pasteme-cli/overall (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pasteme/.virtualenvs/pasteme.pythonanywhere.com/lib/python3.8/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/pasteme/.virtualenvs/pasteme.pythonanywhere.com/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/pasteme/.virtualenvs/pasteme.pythonanywhere.com/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/pasteme/.virtualenvs/pasteme.pythonanywhere.com/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/pasteme/.virtualenvs/pasteme.pythonanywhere.com/lib/python3.8/site-packages/requests/adapters.py", line 559, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='pypistats.org', port=443): Max retries exceeded with url: /api/packages/pasteme-cli/overall (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))
```

However, my script works perfectly on my local machine!

**Comment by lnxpy** [comment]
You can also create a begginer account on PythonAnyWhere and try it on your own!! That's kinda weird!

**Comment by hugovk** [comment]
Because you also get the 403 calling the API directly, please raise it at https://github.com/crflynn/pypistats.org

But you might be better off raising it with PythonAnywhere, as it seems to be related to some proxying at their end?

**Comment by lnxpy** [comment]
Yes, you are right. PythonAnyWhere is blocking all outside services by default and I needed to ask them to add pypistats to their whitelist so that all users can use its endpoints. My issue is fixed though. Thanks. <3
