### ISSUE TITLE
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 0-38: ordinal not in range(256)

### ISSUE THREAD

**Issue by YarShev** [hugovk/pypistats#417]
Hi there,

I wanted to collect some statistics of a package with pypistats but encountered the error.

```pytb
$ python -m pip install --upgrade pypistats
$ pypistats recent pandas
Traceback (most recent call last):
  File "miniconda3/envs/myenv/bin/pypistats", line 8, in <module>
    sys.exit(main())
  File "miniconda3/envs/myenv/lib/python3.9/site-packages/pypistats/cli.py", line 372, in main
    args.func(args)
  File "miniconda3/envs/myenv/lib/python3.9/site-packages/pypistats/cli.py", line 217, in recent
    print(
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 0-39: ordinal not in range(256)
```

Is there something I am doing wrong?

**Comment by hugovk** [comment]
Maybe it's something to do with"colour" codes to make the headers bold. 

What OS/terminal are you using?

Does `NO_COLOR=1 pypistats recent pandas` work for you?

![image](https://github.com/hugovk/pypistats/assets/1324225/1cf08788-6012-445d-af34-23cd15906d6f)

And do other `--format`s work?

![image](https://github.com/hugovk/pypistats/assets/1324225/05892bf6-6ef9-46a5-b584-60f223594fc2)

**Comment by YarShev** [comment]
> What OS/terminal are you using?

Ubuntu 22.04.3 LTS, terminal putty and tmux as a terminal multiplexer.

> Does NO_COLOR=1 pypistats recent pandas work for you?

Same error

> And do other --formats work?

Other formats work for me. It looks like the problem is only related to `pretty` option.

**Comment by hugovk** [comment]
pypistats.org data is available for the [last 180 days](https://pypistats.org/about#data). (For longer time periods, [pypinfo](https://github.com/ofek/pypinfo) can help, you'll need an API key and get free quota.)

**Comment by YarShev** [comment]
Okay, thanks! Should this issue still be open as there is a problem with `pretty` option?

**Comment by hugovk** [comment]
Can do, would you like to try editing `miniconda3/envs/myenv/lib/python3.9/site-packages/pypistats/__init__.py` and replace both `SINGLE_BORDER` with another option such as `DEFAULT`?

https://github.com/jazzband/prettytable#setting-a-table-style

For example:

```console
❯ pypistats recent pandas
+-----------+-------------+------------+
|  last_day |  last_month |  last_week |
+-----------+-------------+------------+
| 6,129,470 | 144,080,301 | 36,288,468 |
+-----------+-------------+------------+
```

I'm wondering if it's one of the border characters, and we should probably do some encoding somewhere.

**Comment by YarShev** [comment]
After replacing `SINGLE_BORDER` to `DEFAULT` the issue has gone.
